### ISSUE TITLE
Implementação dos Estilos da Pagina de Promoção [30pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#11]
Tarefa interligada com GoodPay #5 Verificar se os estilos da página e propor melhorias na visão geral da página de promoções.
![image](https://user-images.githubusercontent.com/31005408/164026118-b0194709-644d-4500-accf-aecca4ffa77f.png)
![image](https://user-images.githubusercontent.com/31005408/164026133-ddd48c56-6df4-44e4-b0ac-4704cc8e7c0b.png)
![image](https://user-images.githubusercontent.com/31005408/164026149-b6709619-593b-4753-93e2-7edd59076685.png)
![image](https://user-images.githubusercontent.com/31005408/164026174-b3ffd68c-7191-4eb9-81b4-7f5e19455522.png)
![image](https://user-images.githubusercontent.com/31005408/164026484-99863ba5-b6d0-486e-9299-490d96c39025.png)

As melhorias podem ser com uso de modal ou carrosséis e demais recursos do Bootstrap

**Comment by natycavaillier** [comment]
Branch com Estilização na página de Promoções. Créditos: Jaqueline, Ivan, Maria Fernanda, Carlos Eduardo, Erivelton, Natália, Bianca Gonçalves
