### ISSUE TITLE
Implementar uma Página de Quem Somos [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#12]
Criar página quem somos com nome de arquivo somos.html, criar um link para página adicionado a um botão na aba de BCW18 no menu principal. Utilize como base o menu e o nav da página app.html

Onde deve ficar:
![image](https://user-images.githubusercontent.com/31005408/164025478-cc579834-2357-422d-a078-798350440af8.png)
![image](https://user-images.githubusercontent.com/31005408/164025733-3ab80f93-9e85-4dc4-b9e5-6ac9cb5e8c00.png)

**Comment by Bruunaa** [comment]
Implementamos a página  com o auxílio e ajuda todos.
