### ISSUE TITLE
Adição do Carrossel de Banners com uso de Slide [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#14]
Devemos utilizar o recurso do Bootstrap para que o banner tenha movimento baseado nas funções apresentas na documentação. O banner deverá transitar entre os elementos da página de banners da promoções.

Exemplo da Documentação:
![image](https://user-images.githubusercontent.com/31005408/164028622-eb07e9cb-59a3-42d8-9745-01782604533e.png)
![image](https://user-images.githubusercontent.com/31005408/164029282-f6cf9f78-94fc-4bcd-a326-9757f06ce650.png)

Localização do Banner Carrossel:

**Comment by soulcode-acad** [comment]
Olá pessoal passando para indicar que estou acompanhando os processos de versionamento, desejo ótimo termino desta primeira sprint de projetos de você!

**Comment by victoriaaraujo10** [comment]
Adição do Carrossel de Banners com uso de Slide.
Deixamos todos os cards com o mesmo width para melhor visualização do usuário, antes o tamanho dos cards era baseado no tamanho dos textos, agora há um padrão.
Créditos: Pâmela.
