### ISSUE TITLE
Adição de Modal para o Card de "Poupe no Cartão e Ganhe na vida" [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#16]
Com base nos cartões utilizados na landpage devemos estruturar modais largos como prevê a documentação para apresentar material para os 3 cards da página inicial. Lembrando que somente no modal que o título esta no texto entre aspas da tarefa.
Documentação de uso do Bootstrap em Modal Large
![image](https://user-images.githubusercontent.com/31005408/164029977-50b66597-cc0a-4c83-8896-719902c11af3.png)
Modal implementado com base sistema da landpage:
![image](https://user-images.githubusercontent.com/31005408/164030210-0987ccfb-89cf-4d25-8de7-ee587b411b61.png)
os links devem estar em botões ou nas imagens para abrir o modal. Use com criatividade o recurso de modal.

**Comment by robunye** [comment]
Adição de Modal para o Card de Poupe no Cartão e Ganhe na Vida

Créditos:
Alliny Benvindo
Bruno Gabriel Aquino
Egla Fernandes
Gabriel Moraes
Iara Beco
Luiz Martins
Roberta Coelho
