### ISSUE TITLE
Adição da Página de Recuperar Senha [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#2]
Uma página de recuperação de senha, montada com seguinte modelo na imagem a seguir: nome do arquivo recuperar.html
![image](https://user-images.githubusercontent.com/31005408/164010686-9d5dfc6d-843c-4357-a21e-390c043baa86.png)
Estilo do formulário:
![image](https://user-images.githubusercontent.com/31005408/164010785-9395c833-a19f-45e7-94c8-a4b7e681ba66.png)

**Comment by Danrley-dev** [comment]
Branch adição da página de recuperação de senha. 
Créditos: João codando e os demais ajudando na contrução do mesmo

**Comment by victoricoma** [comment]
@Danrley-dev  esqueceu de vincular a tarefa com a entrega!
