### ISSUE TITLE
Montar um Sistema validação Anti-Robô [150pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#23]
Esta tarefa requer conhecimento adicional do https://soulcodeacademy.teachable.com/ aulas de DOM e ainda complementos de tarefas e implementação de Javascript ,com Bootstrap e HTML. esta tarefa requer estudo fora do conteúdo passado e é proposta como desafio.

Esta tarefa deverá se comunicar com os squads das tarefas GoodPay #9 e GoodPay #10 sem esta comunicação poderá gerar erros em ambos os cartões.

O Sistema deverá mostrar um campo de validação por calculo
![image](https://user-images.githubusercontent.com/31005408/164034524-dc254059-934b-419e-a3e4-fcee968dcb32.png)

Código de Referência do App original do Professor verificar login e validar código:
loginInfo(user, senha, recaptcha) {
    localStorage.clear()
    let infoCheck = userLogin.find(userLogin => userLogin.username === user)

    // Função para encontrar o usuário Admin
    function findAdmin(user) {
      return user.id === '1003'
    }

    if (
      user === null ||
      senha === null ||
      user === '' ||
      senha === '' ||
      recaptcha === null ||
      recaptcha === ''
    ) {
      this.checkOutLogin()
      localStorage.status = this.status
      return comunicacaoModal.find(i => i.idModal === 'camposVazios1')
    } else if (!infoCheck) {
      this.checkOutLogin()
      localStorage.status = this.status
      return comunicacaoModal.find(i => i.idModal === 'usuarioNaoExiste1')
    } else if(
      // Verifica se senha e usuário são do superRotas
      infoCheck.senha === senha && infoCheck.username === "superRotas"
      ) {
      comunicacaoModal.find((comunicacaoModal) => comunicacaoModal.idModal === "listaRotas").bodyModal = controleRotasApp.listarRota();
      return (comunicacaoModal.find((comunicacaoModal) => comunicacaoModal.idModal === "listaRotas"));
    } else if (
      // Verifica se senha e usuário são do admin
      user === userLogin.find(findAdmin).username &&
      senha === userLogin.find(findAdmin).senha
    ) {
      this.checkLogin()
      localStorage.status = this.status
      return comunicacaoModal.find(
        comunicacaoModal => comunicacaoModal.idModal === 'adminListaUsuario1'
      )
    } else {
      if (infoCheck.senha === senha && recaptcha == this.resultReference) {
        //Senha e recaptcha precisam estar corretos
        this.checkLogin()
        localStorage.status = this.status
        localStorage.email = infoCheck.email
        localStorage.userName = infoCheck.username

        return comunicacaoModal.find(i => i.idModal === 'loginExecutado1')
      } else {
        this.attempts++
        if (this.attempts !== 3) {
          //Máximo de tentativas
          this.checkOutLogin()
          localStorage.status = this.status
          let tentativasObject = comunicacaoModal.find(
            i => i.idModal === 'tentativasDemais1'
          )
          //Passando o resto das tentativas para o usuário
          tentativasObject.bodyModal = `Error#1022 - Você já fez ${this.attempts} tentativa(s)! Com três será redirecionado(a) para recuperar senha`;
          return tentativasObject
        } else {
          this.attempts = 0
          this.checkOutLogin()
          localStorage.status = this.status
          return comunicacaoModal.find(i => i.idModal === 'falhaLogin1')
        }
      }
    }
  }

  numberGenerator() {
    //gerador de números aleatorios para recaptcha
    let logicalOperator1 = Math.floor(Math.random() * 300)
    let logicalOperator2 = Math.floor(Math.random() * 10)
    let result = [
      {
        num01: logicalOperator1,
        num02: logicalOperator2,
        sum: logicalOperator1 + logicalOperator2
      }
    ]
    this.resultReference = result[0].sum
    return result
  }

Todas estas funções são validas na index.js

**Comment by soulcode-acad** [comment]
Olá pessoal passando para indicar que estou acompanhando os processos de versionamento, desejo ótimo termino desta primeira sprint de projetos de você!

**Comment by robunye** [comment]
Implementação do sistema de validação anti-robô

Créditos: 
Alliny Benvindo
Bruno Gabriel Aquino
Egla Fernandes
Gabriel Moraes
Iara Beco
Luiz Martins
Roberta Coelho
