### ISSUE TITLE
Adição de Classe para compatibilidade de telas ultrawide [30pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#25]
Editar uma classe em CSS para compatibilizar a visualização de ultrawide com a aplicação GoodPay.

Sugestão de Código:
`.trancaTela{
    max-width: 1080px;
    margin: 0 auto;
}`

![image](https://user-images.githubusercontent.com/31005408/164264662-82a6d777-70ad-45f4-a652-4e26ed71da4a.png)

**Comment by henriqueburgos** [comment]
Branch adção de classe  de vizualização UltraWide.  Creditos : Tawan.
