### ISSUE TITLE
Verificação de outras telas e suas compatibilidades ultrawide [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#26]
Verificação se as telas de index.html, registro.html, recupera.html estão seguindo o padrão de trancar a tela para visualizações ultrawide.

`.trancaTela{
    max-width: 1080px;
    margin: 0 auto;
}`

![image](https://user-images.githubusercontent.com/31005408/164265309-177a5cee-15d4-4240-9766-7db05f8932c5.png)
![image](https://user-images.githubusercontent.com/31005408/164265579-fde50dd9-8d05-4816-9707-c2b6c138af8b.png)

**Comment by BetoMax2022** [comment]
Tdoso participaram na solução de telas UltraWide
Todos participaram na solução de data atual nos Cards
