### ISSUE TITLE
Adição do  Menu de Ajuda [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#3]
Esta tarefa tem vinculo com GoodPay#4 Nesta tarefa devemos ajustar um novo item no menu lateral de todas as páginas que tenham vinculados o menu. Esta tarefa trabalha em conjunto com todas de adição de páginas.
Estilo do implemento.
![image](https://user-images.githubusercontent.com/31005408/164012181-c55e8cf6-79d2-47b1-b6a5-dcd3fce8f4ed.png)

**Comment by soulcode-acad** [comment]
Olá pessoal passando para indicar que estou acompanhando os processos de versionamento, desejo ótimo termino desta primeira sprint de projetos de você!

**Comment by natycavaillier** [comment]
Branch para adição do menu de ajuda em todas as páginas existentes. Créditos: Jaqueline, Ivan, Maria Fernanda, Carlos Eduardo, Erivelton, Natália, Bianca Gonçalves
