### ISSUE TITLE
Criação da Página de Cadastro com Bootstrap

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/goodpay#32]
- [x] Faça uma clonagem do repositório victoricoma/goodplay.
- [x] Tenha certeza que está com base aplicada no repositório do projeto.
- [x] Certifique que sua branch está atualizada e compatível com dos outros grupos. 
- [x] Se comunique-se com os outros grupos para evitar subscrever os trabalhos.
- [x] Observe a data da solicitação e cuidado ao alterar elementos fora de sua implementação.
- [x] Montar o NavBar idêntico a como está no FaceShild da Aplicação.
- [x] Montar o Offcanvas idêntico ao que está no FaceShild da aplicação.
- [x] Criar os campos de criação de acordo com as informações do módulodados.
- [x] Criar os campos de imput usando as características do Bootstrap.
- [x] Organizar de forma que o Layout fique compatível com a faceShild do Aplicativo.
- [x] Manter a identidade visual.
- [x] Não precisa construir os módulos e a parte de adição via Javascript.
- [x] Subir para o repositório com uma branch de nome telaCriarCadastro e aguardar PR aprovação de Merge do @victoricoma .

![image](https://user-images.githubusercontent.com/31005408/147147424-1d43abad-ef51-4370-a42a-8dcae0e07151.png)

Link para lousas: https://drive.google.com/drive/folders/14b7FJPpH0napMI8fiZDbK8Er1KQIzlgh?usp=sharing

**Comment by valleriabueno** [comment]
@valleriabueno 
Implementação para @victoricoma @jrcodev

- [ ]  Implementada tela de Cadastro
- [ ] Implementado Modal para Termos de Uso
- [ ] Elaboradas instruções para Registro de Usuário (Issue#35)
- [ ] Efetuados testes e correções para responsividade aprimorada
