### ISSUE TITLE
Adição dos Modais de Ajuda [60pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#4]
Este link deve montar um modal para cada possível erro da aplicação:
Estilo do modal de ajuda.
![image](https://user-images.githubusercontent.com/31005408/164012403-8cd3a820-c8af-42af-bb9f-6f8d134978c4.png)
Cada Erro deve ter um tratamento de Ajuda.

**Comment by Danrley-dev** [comment]
branch: Adição dos modais de ajuda. Creditos Danrley codando e os demais auxiliando no desenvolvimento e pesquisa do projeto
