### ISSUE TITLE
Bug na implementação da PR #41

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/goodpay#48]
- [x] Revisar a passagem de parâmetros para tela app.html
- [x] Analisar o badge com problema.
- [x] Corrigir o bug.
- [x] PR #43 olhar o que pode ter falhado no conversão.
- [x] Entrar no fim da fila para PR.

Revisão até dia 02 de janeiro.

**Comment by victoricoma** [comment]
@brunodiascultural e @FelipeMarques06 resolvam o problema com a PR #44 por favor ambos os grupos serão bonificados por resolução com diplomacia entre as implementações.

**Comment by Lucianocbarbosa** [comment]
@FelipeMarques06 tivemos que colocar sua função da index.js através de um switch para evitar um erro de múltiplas execuções:

- [ ] Verificar se não teve alteração na sua function "adicionarBloco()";
- [ ] Verificar se o switch implementado funciona com a sua lógica de programação;
- [ ] Fazer o teste humano na sua função.
- [ ] #43 
- [ ] #46
