### ISSUE TITLE
Implementação dos Estilos do Formulário de Cadastro [30pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#6]
Vinculada a tarefa GoodPay #1 devemos impor melhorias e certificar uso das melhores técnicas de Bootstrap para a página de cadastro. 
![image](https://user-images.githubusercontent.com/31005408/164014291-e0fb01a3-276c-4f1c-81c1-daa1e12bb92a.png)

**Comment by soulcode-acad** [comment]
Olá pessoal passando para indicar que estou acompanhando os processos de versionamento, desejo ótimo termino desta primeira sprint de projetos de você!
