### ISSUE TITLE
Implementar um validação com IF e Array para o Login utilizando JS [150pts]

### ISSUE THREAD

**Issue by victoricoma** [victoricoma/GoodPay#9]
Esta tarefa requer conhecimento adicional do https://soulcodeacademy.teachable.com/ aulas de DOM e ainda complementos de tarefas e implementação de Javascript ,com Bootstrap e HTML. esta tarefa requer estudo fora do conteúdo passado e é proposta como desafio.
![image](https://user-images.githubusercontent.com/31005408/164019409-d9371ed5-bb1d-420d-9bf2-40e6b182eb9a.png)
Com base nas informações deste campo a index.js deve mapear um vetor de usuários pré-definidos e validar se o usuário está presente no vetor, ao final deve encaminhar o usuário para página index.html copia idêntica da app.html.
Vetor de Objetos para Validação.
![image](https://user-images.githubusercontent.com/31005408/164020512-023f142c-5a0f-44c2-bf35-7861764e6485.png)
Código em Javascript para executar o Login:
loginInfo(user, senha, recaptcha) {
    localStorage.clear()
    let infoCheck = userLogin.find(userLogin => userLogin.username === user)

    // Função para encontrar o usuário Admin
    function findAdmin(user) {
      return user.id === '1003'
    }

    if (
      user === null ||
      senha === null ||
      user === '' ||
      senha === '' ||
      recaptcha === null ||
      recaptcha === ''
    ) {
      this.checkOutLogin()
      localStorage.status = this.status
      return comunicacaoModal.find(i => i.idModal === 'camposVazios1')
    } else if (!infoCheck) {
      this.checkOutLogin()
      localStorage.status = this.status
      return comunicacaoModal.find(i => i.idModal === 'usuarioNaoExiste1')
    } else if(
      // Verifica se senha e usuário são do superRotas
      infoCheck.senha === senha && infoCheck.username === "superRotas"
      ) {
      comunicacaoModal.find((comunicacaoModal) => comunicacaoModal.idModal === "listaRotas").bodyModal = controleRotasApp.listarRota();
      return (comunicacaoModal.find((comunicacaoModal) => comunicacaoModal.idModal === "listaRotas"));
    } else if (
      // Verifica se senha e usuário são do admin
      user === userLogin.find(findAdmin).username &&
      senha === userLogin.find(findAdmin).senha
    ) {
      this.checkLogin()
      localStorage.status = this.status
      return comunicacaoModal.find(
        comunicacaoModal => comunicacaoModal.idModal === 'adminListaUsuario1'
      )
    } else {
      if (infoCheck.senha === senha && recaptcha == this.resultReference) {
        //Senha e recaptcha precisam estar corretos
        this.checkLogin()
        localStorage.status = this.status
        localStorage.email = infoCheck.email
        localStorage.userName = infoCheck.username

        return comunicacaoModal.find(i => i.idModal === 'loginExecutado1')
      } else {
        this.attempts++
        if (this.attempts !== 3) {
          //Máximo de tentativas
          this.checkOutLogin()
          localStorage.status = this.status
          let tentativasObject = comunicacaoModal.find(
            i => i.idModal === 'tentativasDemais1'
          )
          //Passando o resto das tentativas para o usuário
          tentativasObject.bodyModal = `Error#1022 - Você já fez ${this.attempts} tentativa(s)! Com três será redirecionado(a) para recuperar senha`;
          return tentativasObject
        } else {
          this.attempts = 0
          this.checkOutLogin()
          localStorage.status = this.status
          return comunicacaoModal.find(i => i.idModal === 'falhaLogin1')
        }
      }
    }
  }

**Comment by henriqueburgos** [comment]
Branch de implementação de validação com IF e Array para o Login utilizando JS 
Creditos
Tawan Silva
